name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    name: "Merge"
    runs-on: ubuntu-latest
    steps:
      - name: "Merge"
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
